name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      name: npm install
        env:
          CI: true
        run:
          npm ci